import { expect, test } from '@playwright/test'
import { fourBallFixture } from './fourBallSupport'
import { offlineEvents, offlineLayout, queueRows } from './offlineSupport'
import { decodePending } from '../src/features/scoring/offline/decode'

test.skip(process.env.GOLF_FOUR_BALL_BROWSER !== '1', 'Requires disposable local API and Chrome')
test('four-ball partner inputs, pickups, offline conflicts, confirmation and preserved history', async ({ page, browser }) => {
  const fixture = await fourBallFixture(page, browser)
  const events = offlineEvents(page)
  await page.goto(fixture.url())
  const partners = page.locator('.four-ball-partner')
  await expect(partners).toHaveCount(2)
  await offlineLayout(page, 'four-ball-empty')
  await partners.nth(0).getByRole('button', { name: 'Registrer par (4)' }).click()
  await expect.poll(async () => (await fixture.read()).holes_scored).toBe(1)
  await partners.nth(1).getByRole('button', { name: 'Registrer par (4)' }).click()
  await expect.poll(async () => (await fixture.read()).holes[0]?.net?.player_ids).toEqual([fixture.secondId])
  await expect.poll(async () => (await queueRows(page)).length).toBe(0)
  await offlineLayout(page, 'four-ball-populated')
  const before = (await fixture.read()).holes[0]?.players.find(player => player.player_id === fixture.secondId)?.score
  await partners.nth(1).getByRole('button', { name: 'Plukket opp', exact: true }).click()
  await partners.nth(1).getByRole('button', { name: 'Ja, plukket opp' }).click()
  await expect.poll(async () => (await fixture.read()).holes[0]?.players.find(player => player.player_id === fixture.secondId)?.score?.input.type).toBe('no_score')
  const pickup = (await fixture.read()).holes[0]?.players.find(player => player.player_id === fixture.secondId)?.score
  expect(pickup?.id).toBe(before?.id)
  await expect.poll(async () => (await queueRows(page)).length).toBe(0)
  await expect(partners.nth(1).getByRole('button', { name: 'Registrer par (4)' })).toBeEnabled()
  await page.context().setOffline(true)
  await partners.nth(1).getByRole('button', { name: 'Registrer par (4)' }).click()
  await expect.poll(async () => (await queueRows(page)).length).toBe(1)
  const local = decodePending((await queueRows(page))[0])
  expect(local.protocol).toBe('four_ball_v1')
  expect(local.head.expected_score).toEqual({ type: 'present', score_id: pickup?.id, revision: pickup?.revision })
  await offlineLayout(page, 'four-ball-offline')
  await fixture.save(1, fixture.secondId, { type: 'numeric', gross_strokes: 6 })
  await page.context().setOffline(false)
  await page.locator('#pending-scores summary').click()
  await page.getByRole('button', { name: 'Sammenlign scorer' }).click()
  await expect(page.getByText('Score på serveren:')).toContainText('6 slag')
  await page.getByRole('button', { name: 'Behold serverscoren' }).click()
  await expect.poll(async () => (await queueRows(page)).length).toBe(0)
  await expect(partners.nth(1).getByRole('button', { name: 'Registrer par (4)' })).toBeEnabled()
  await page.context().setOffline(true)
  await partners.nth(1).getByRole('button', { name: 'Plukket opp', exact: true }).click()
  await partners.nth(1).getByRole('button', { name: 'Ja, plukket opp' }).click()
  await expect.poll(async () => (await queueRows(page)).length).toBe(1)
  await fixture.save(1, fixture.secondId, { type: 'numeric', gross_strokes: 7 })
  await page.context().setOffline(false)
  await page.getByRole('button', { name: 'Sammenlign scorer' }).click()
  await expect(page.getByText('Din lokale score:')).toContainText('Plukket opp')
  await page.getByRole('button', { name: 'Bruk min lokale score' }).click()
  await expect.poll(async () => (await queueRows(page)).length).toBe(0)
  await expect.poll(async () => (await fixture.read()).holes[0]?.players.find(player => player.player_id === fixture.secondId)?.score?.input.type).toBe('no_score')
  for (let hole = 2; hole <= 18; hole++) await fixture.save(hole, fixture.firstId, { type: 'numeric', gross_strokes: 4 })
  await page.getByRole('button', { name: 'Oppsummering', exact: true }).click()
  const confirm = page.getByRole('button', { name: 'Bekreft lagets scorekort' })
  await expect(confirm).toBeDisabled()
  await page.getByLabel('Jeg bekrefter at tomme partnerfelt ikke bidrar med score.').check()
  await expect(confirm).toBeEnabled()
  await offlineLayout(page, 'four-ball-summary')
  await confirm.click()
  await expect.poll(async () => (await fixture.read()).confirmed).toBe(true)
  await fixture.mutate(`/api/rounds/${fixture.round.id}/complete`)
  await page.goto(fixture.url())
  await page.getByRole('button', { name: 'Korriger score' }).click()
  await partners.nth(0).getByRole('button', { name: 'Plukket opp', exact: true }).click()
  await partners.nth(0).getByRole('button', { name: 'Ja, plukket opp' }).click()
  await expect(page.getByText(/Rundens resultat teller ikke sammenlagt/)).toBeVisible()
  await partners.nth(0).getByRole('button', { name: 'Registrer par (4)' }).click()
  await expect.poll(async () => (await fixture.read()).complete).toBe(true)
  await fixture.mutate(`${fixture.cardPath}/confirm`)
  await fixture.mutate(`/api/rounds/${fixture.round.id}/lock`)
  await page.goto(`/tournaments/${fixture.tournament.id}/rounds/${fixture.round.id}/scorecards/team/${fixture.teamId}?metric=net&view=summary`)
  await expect(page.getByRole('heading', { name: fixture.card.owner_name })).toBeVisible()
  await page.getByRole('button', { name: 'Hull 2 · par 4', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Hull 2 · par 4 · indeks 2' })).toBeVisible()
  await offlineLayout(page, 'four-ball-private-history')
  expect(events.errors).toEqual([])
  expect(events.statuses.filter(status => ![401, 409].includes(status))).toEqual([])
  expect(events.failures.every(message => /ERR_INTERNET_DISCONNECTED|ERR_NETWORK_CHANGED|ERR_ABORTED|ERR_FAILED|aborted/i.test(message))).toBe(true)
})

test('four-ball loading and failed side reads offer retry without hiding the selected team', async ({ page, browser }) => {
  const fixture = await fourBallFixture(page, browser)
  const events = offlineEvents(page)
  let release = () => undefined as void
  const wait = new Promise<void>(resolve => { release = resolve })
  await page.route(`**${fixture.cardPath}/scoring`, async route => { await wait; await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'unavailable', message: 'Temporary unavailable' }) }) })
  await page.goto(fixture.url())
  await expect(page.getByText('Laster …', { exact: true })).toBeVisible()
  await offlineLayout(page, 'four-ball-loading')
  release()
  await expect(page.getByRole('alert')).toBeVisible()
  await offlineLayout(page, 'four-ball-error')
  await page.unroute(`**${fixture.cardPath}/scoring`)
  await page.getByRole('button', { name: 'Prøv igjen', exact: true }).click()
  await expect(page.locator('.four-ball-partner')).toHaveCount(2)
  expect(events.errors).toEqual([])
})

test('four-ball retains a lost acknowledgement and successor across reload and a second tab', async ({ page, browser, context }) => {
  const fixture = await fourBallFixture(page, browser)
  const events = offlineEvents(page)
  await page.goto(fixture.url())
  await expect(page.locator('.four-ball-partner')).toHaveCount(2)
  let loseFirst = true, allowDelivery = false
  await context.route('**/four-ball/inputs/conditional', async route => {
    if (loseFirst) {
      loseFirst = false
      const result = await route.fetch()
      expect(result.ok()).toBe(true)
      await route.abort('connectionreset')
    } else if (!allowDelivery) await route.fulfill({ status: 503, json: { error: { code: 'unavailable', message: 'Temporary unavailable' } } })
    else await route.continue()
  })
  const partner = page.locator('.four-ball-partner').nth(0)
  await partner.getByRole('button', { name: 'Registrer par (4)' }).click()
  await expect.poll(async () => (await fixture.read()).holes_scored).toBe(1)
  await expect.poll(async () => (await queueRows(page)).length).toBe(1)
  const original = decodePending((await queueRows(page))[0])
  const saved = (await fixture.read()).holes[0]?.players.find(player => player.player_id === fixture.firstId)?.score
  await partner.getByRole('button', { name: /Ett slag mer/ }).click()
  await expect.poll(async () => {
    const item = decodePending((await queueRows(page))[0])
    return item.protocol === 'four_ball_v1' && item.desired.type === 'numeric' ? item.desired.gross_strokes : null
  }).toBe(5)
  expect(decodePending((await queueRows(page))[0]).head).toEqual(original.head)
  await page.reload()
  await expect(page.locator('.four-ball-partner').nth(0).locator('p[role="status"]')).toContainText('Lokalt: 5 slag')
  const second = await context.newPage()
  try {
    await second.goto(fixture.url())
    await expect(second.locator('.four-ball-partner').nth(0).locator('p[role="status"]')).toContainText('Lokalt: 5 slag')
    expect(decodePending((await queueRows(second))[0]).head).toEqual(original.head)
    allowDelivery = true
    await page.evaluate(() => window.dispatchEvent(new Event('online')))
    await second.evaluate(() => window.dispatchEvent(new Event('online')))
    await expect.poll(async () => (await queueRows(page)).length, { timeout: 35_000 }).toBe(0)
    const latest = (await fixture.read()).holes[0]?.players.find(player => player.player_id === fixture.firstId)?.score
    expect(latest?.id).toBe(saved?.id)
    expect(latest?.revision).toBe('2')
    expect(latest?.input).toEqual({ type: 'numeric', gross_strokes: 5 })
    await expect(page.locator('.four-ball-partner').nth(0).locator('p[role="status"]')).toHaveText('Synkronisert')
    await expect(second.locator('.four-ball-partner').nth(0).locator('p[role="status"]')).toHaveText('Synkronisert')
  } finally { await second.close(); await context.unroute('**/four-ball/inputs/conditional') }
  expect(events.errors).toEqual([])
})

test('four-ball storage failure keeps the unsaved edit guarded and discard remains usable', async ({ page, browser }) => {
  const fixture = await fourBallFixture(page, browser)
  const events = offlineEvents(page)
  await page.goto(fixture.url())
  await expect(page.locator('.four-ball-partner')).toHaveCount(2)
  await page.evaluate(() => {
    const original = IDBObjectStore.prototype.put
    IDBObjectStore.prototype.put = function(value: unknown, key?: IDBValidKey) {
      if (this.name === 'pending') throw new DOMException('Storage unavailable', 'QuotaExceededError')
      return key === undefined ? original.call(this, value) : original.call(this, value, key)
    }
  })
  await page.locator('.four-ball-partner').nth(1).getByRole('button', { name: 'Registrer par (4)' }).click()
  await expect(page.getByText(/Endringen er ikke trygt lagret/).first()).toBeVisible()
  await expect(page.getByRole('button', { name: 'Neste hull' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Oppsummering', exact: true })).toBeDisabled()
  await offlineLayout(page, 'four-ball-storage-failure')
  await page.getByRole('button', { name: 'Forkast ulagret endring' }).click()
  await expect(page.getByRole('button', { name: 'Neste hull' })).toBeEnabled()
  await page.getByRole('button', { name: 'Neste hull' }).click()
  await expect(page.getByRole('heading', { name: 'Hull 2 · par 4 · indeks 2' })).toBeVisible()
  expect(await queueRows(page)).toEqual([])
  expect(events.errors).toEqual([])
})
