import { expect, test, type Page } from '@playwright/test'
import { offlineEvents, offlineFixture, offlineLayout, queueRows } from './offlineSupport'

test.skip(process.env.GOLF_OFFLINE_BROWSER !== '1', 'Requires disposable local API and GOLF_OFFLINE_BROWSER=1.')
test.use({ screenshot: 'off', trace: 'off' })

async function signIn(page: Page, username: string, password: string) {
  await page.goto('/login')
  await page.getByLabel('Brukernavn', { exact: true }).fill(username)
  await page.getByLabel('Passord', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Logg inn', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Logg ut' })).toBeVisible()
}
test('retains queued data on logout but hides it from another account and resumes with a new session', async ({ page, context, browser }) => {
  const fixture = await offlineFixture(page)
  const secondContext = await browser.newContext({ baseURL: 'http://127.0.0.1:5173' })
  const secondPage = await secondContext.newPage()
  const second = await offlineFixture(secondPage)
  const events = offlineEvents(page)
  try {
    await page.goto(fixture.url())
    await expect(page.getByRole('button', { name: /Registrer par/ })).toBeEnabled()
    await context.setOffline(true)
    await page.getByRole('button', { name: 'Legg til ett slag' }).click()
    await expect.poll(async () => (await queueRows(page)).length).toBe(1)
    await page.route('**/scores/conditional', route => route.fulfill({ status: 503, json: { error: { code: 'unavailable', message: 'unavailable' } } }))
    await context.setOffline(false)
    await page.getByRole('button', { name: 'Logg ut' }).click()
    await expect(page.getByRole('button', { name: 'Logg inn', exact: true })).toBeVisible()
    await signIn(page, second.username, second.password)
    await page.goto(second.url())
    await expect(page.locator('.pending-scores summary')).toContainText('(0)')
    expect(await queueRows(page)).toHaveLength(1)
    expect((await second.read()).holes[0]?.score).toBeNull()
    await offlineLayout(page, 'different-account')
    await page.getByRole('button', { name: 'Logg ut' }).click()
    await page.unroute('**/scores/conditional')
    await signIn(page, fixture.username, fixture.password)
    await page.goto(fixture.url())
    await expect.poll(async () => (await queueRows(page)).length, { timeout: 35_000 }).toBe(0)
    await expect(page.locator('.score-stepper output strong')).toHaveText('5')
    await expect(page.getByText('Lagret på serveren', { exact: true })).toBeVisible()
    expect(events.errors).toEqual([])
  } finally { await secondContext.close() }
})

test('device write failure never claims durability and guards navigation until explicitly discarded', async ({ page }) => {
  const fixture = await offlineFixture(page); const events = offlineEvents(page)
  await page.goto(fixture.url())
  await expect(page.getByRole('button', { name: /Registrer par/ })).toBeEnabled()
  await page.evaluate(() => {
    const put = IDBObjectStore.prototype.put
    IDBObjectStore.prototype.put = function (value: unknown, key?: IDBValidKey) {
      if (this.name === 'pending') throw new DOMException('Device storage full', 'QuotaExceededError')
      return key === undefined ? put.call(this, value) : put.call(this, value, key)
    }
  })
  await page.getByRole('button', { name: /Registrer par/ }).click()
  await expect(page.getByText('Ikke lagret på enheten', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Neste' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Logg ut' })).toBeDisabled()
  expect(await queueRows(page)).toHaveLength(0)
  await offlineLayout(page, 'storage-failure')
  await page.getByRole('button', { name: 'Forkast', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Neste' })).toBeEnabled()
  await page.getByRole('button', { name: 'Neste' }).click()
  await expect(page.locator('#current-hole-heading')).toHaveText('2')
  expect(events.errors).toEqual([])
})

test('confirmed completed cards support explicit offline correction; a later lock retains a discardable blocked edit', async ({ page, context }) => {
  const fixture = await offlineFixture(page); const events = offlineEvents(page)
  for (let number = 1; number <= 18; number += 1) await fixture.save(number, 4)
  await fixture.mutate(`/api/rounds/${fixture.round.id}/scorecards/player/${fixture.owner.id}/confirm`)
  await fixture.mutate(`/api/rounds/${fixture.round.id}/complete`)
  await page.goto(fixture.url())
  await expect(page.getByRole('button', { name: 'Korriger score' })).toBeEnabled()
  await context.setOffline(true)
  await page.getByRole('button', { name: 'Korriger score' }).click()
  await page.getByRole('button', { name: 'Legg til ett slag' }).click()
  await expect.poll(async () => (await queueRows(page)).length).toBe(1)
  await page.getByRole('button', { name: 'Oppsummering', exact: true }).click()
  await expect(page.getByText('Bekreftelse krever forbindelse og at alle lokale endringer er levert.')).toBeVisible()
  await fixture.mutate(`/api/rounds/${fixture.round.id}/lock`)
  await context.setOffline(false)
  await expect(page.locator('.pending-scores summary')).toContainText('krever valg', { timeout: 20_000 })
  await page.locator('.pending-scores summary').click()
  await expect(page.getByText(/Kan ikke leveres med gjeldende tilgang/)).toBeVisible()
  await offlineLayout(page, 'locked-blocked', '.pending-scores')
  await page.getByRole('button', { name: 'Forkast lokal endring' }).click()
  await expect(page.getByText(/Dette angrer ikke en score/)).toBeVisible()
  await page.getByRole('button', { name: 'Ja, fjern lokal kopi' }).click()
  await expect.poll(async () => (await queueRows(page)).length).toBe(0)
  await expect(page.getByText(/Kontrollerer serverscore for/)).toHaveCount(0, { timeout: 20_000 })
  expect(events.errors).toEqual([])
})

test('explicit local discard completes immediately while offline', async ({ page, context }) => {
  const fixture = await offlineFixture(page)
  await page.goto(fixture.url())
  await expect(page.getByRole('button', { name: /Registrer par/ })).toBeEnabled()
  await context.setOffline(true)
  await page.getByRole('button', { name: /Registrer par/ }).click()
  await expect.poll(async () => (await queueRows(page)).length).toBe(1)
  await page.locator('.pending-scores summary').click()
  await page.getByRole('button', { name: 'Forkast lokal endring' }).click()
  await page.getByRole('button', { name: 'Ja, fjern lokal kopi' }).click()
  await expect.poll(async () => (await queueRows(page)).length).toBe(0)
  await expect(page.locator('.pending-scores summary')).toContainText('(0)')
  await context.setOffline(false)
})
