import { expect, test } from '@playwright/test'
import { decodeObject } from '../src/api/decoder'
import { offlineEvents, offlineFixture, offlineLayout, queueRows } from './offlineSupport'

test.skip(process.env.GOLF_OFFLINE_BROWSER !== '1', 'Requires disposable local API and GOLF_OFFLINE_BROWSER=1.')
test.use({ screenshot: 'off', trace: 'off' })

test('real offline holes survive reload, resume and explicitly resolve both conflict choices', async ({ page, context }) => {
  const fixture = await offlineFixture(page); const events = offlineEvents(page)
  await page.goto(fixture.url())
  await expect(page.getByRole('button', { name: /Registrer par/ })).toBeEnabled()
  await offlineLayout(page, 'empty')
  await context.setOffline(true)
  await page.getByRole('button', { name: /Registrer par/ }).click()
  await expect.poll(async () => (await queueRows(page)).length).toBe(1)
  await expect(page.getByRole('button', { name: 'Neste' })).toBeEnabled()
  await page.getByRole('button', { name: 'Neste' }).click()
  await page.getByRole('button', { name: 'Legg til ett slag' }).click()
  await expect.poll(async () => (await queueRows(page)).length).toBe(2)
  await page.getByRole('button', { name: 'Neste' }).click()
  await page.getByRole('button', { name: /Registrer par/ }).click()
  await expect.poll(async () => (await queueRows(page)).length).toBe(3)
  await offlineLayout(page, 'three-holes-collapsed')
  await page.locator('.pending-scores summary').click()
  await expect(page.getByText('Lokalt: 5 slag')).toBeVisible()
  await offlineLayout(page, 'durable-pending', '.pending-scores')
  const serialized = JSON.stringify(await queueRows(page))
  expect(serialized.includes(fixture.auth.csrf_token)).toBe(false)
  expect(serialized.includes(fixture.password)).toBe(false)
  expect(serialized.includes('submitted_by')).toBe(false)
  await page.route('**/scores/conditional', route => route.fulfill({ status: 503, json: { error: { code: 'unavailable', message: 'unavailable' } } }))
  await context.setOffline(false)
  await page.reload()
  await expect(page.locator('#current-hole-heading')).toHaveText('3')
  await expect.poll(async () => (await queueRows(page)).length).toBe(3)
  await page.unroute('**/scores/conditional')
  await page.evaluate(() => window.dispatchEvent(new Event('online')))
  await expect.poll(async () => (await queueRows(page)).length, { timeout: 35_000 }).toBe(0)
  await expect(page.getByText('Lagret på serveren', { exact: true })).toBeVisible()
  expect((await fixture.read()).holes.slice(0, 3).map(hole => hole.score?.gross_strokes)).toEqual([4, 5, 4])
  await page.goto(fixture.url(1))
  await expect(page.getByRole('button', { name: 'Legg til ett slag' })).toBeEnabled()
  await context.setOffline(true)
  await page.getByRole('button', { name: 'Legg til ett slag' }).click()
  await expect.poll(async () => (await queueRows(page)).length).toBe(1)
  await fixture.save(1, 6)
  await context.setOffline(false)
  await expect(page.locator('.pending-scores summary')).toContainText('krever valg', { timeout: 20_000 })
  await page.locator('.pending-scores summary').click()
  await page.getByRole('button', { name: 'Sammenlign scorer' }).click()
  await expect(page.getByText('Score på serveren:')).toContainText('6 slag')
  await offlineLayout(page, 'conflict', '.pending-scores')
  await page.getByRole('button', { name: 'Behold serverscoren' }).click()
  await expect.poll(async () => (await queueRows(page)).length).toBe(0)
  await expect(page.locator('.score-stepper output strong')).toHaveText('6')
  await expect(page.getByRole('button', { name: 'Legg til ett slag' })).toBeEnabled()
  await context.setOffline(true)
  await page.getByRole('button', { name: 'Legg til ett slag' }).click()
  await expect.poll(async () => (await queueRows(page)).length).toBe(1)
  await fixture.save(1, 8)
  await context.setOffline(false)
  await page.getByRole('button', { name: 'Sammenlign scorer' }).click()
  await expect(page.getByText('Score på serveren:')).toContainText('8 slag')
  await page.getByRole('button', { name: 'Bruk min lokale score' }).click()
  await expect.poll(async () => (await queueRows(page)).length).toBe(0)
  await expect.poll(async () => (await fixture.read()).holes[0]?.score?.gross_strokes).toBe(7)
  await expect(page.getByText('Lagret på serveren', { exact: true })).toBeVisible()
  expect(events.errors).toEqual([])
  expect(events.statuses.every(status => [401, 409, 503].includes(status))).toBe(true)
})

test('two tabs retry a lost response and conflict against the acknowledged revision without overwriting a later score', async ({ page, context }) => {
  const fixture = await offlineFixture(page); await fixture.save(1, 4)
  const other = await context.newPage()
  const events = offlineEvents(page); const otherEvents = offlineEvents(other)
  await page.goto(fixture.url()); await other.goto(fixture.url())
  await expect(page.getByRole('button', { name: 'Legg til ett slag' })).toBeEnabled()
  let committed = false; let release = () => undefined as void
  const lost = new Promise<void>(resolve => { release = resolve })
  const requests: { id: unknown; expected: unknown; strokes: unknown }[] = []
  await context.route('**/scores/conditional', async route => {
    const input = decodeObject(route.request().postDataJSON(), 'conditional')
    requests.push({ id: input.request_id, expected: input.expected_score, strokes: input.gross_strokes })
    if (requests.length === 1) {
      const applied = await route.fetch(); expect(applied.status()).toBe(200)
      committed = true
      await lost
      await route.abort('failed')
    } else await route.continue()
  })
  await page.getByRole('button', { name: 'Legg til ett slag' }).click()
  await expect.poll(() => committed).toBe(true)
  await page.getByRole('button', { name: 'Legg til ett slag' }).click()
  await expect.poll(async () => decodeObject((await queueRows(page))[0], 'pending').desired).toBe(6)
  await other.locator('.pending-scores summary').click()
  await expect(other.getByText('Lokalt: 6 slag')).toBeVisible()
  await expect(other.getByRole('button', { name: 'Forkast lokal endring' })).toBeDisabled()
  await fixture.save(1, 9)
  release()
  await expect(other.getByRole('button', { name: 'Sammenlign scorer' })).toBeVisible({ timeout: 35_000 })
  expect(requests.length).toBeGreaterThanOrEqual(3)
  expect(requests[0]?.id).toEqual(requests[1]?.id)
  expect(requests[0]?.expected).toEqual(requests[1]?.expected)
  expect(requests[2]?.id).not.toEqual(requests[0]?.id)
  expect(decodeObject(requests[2]?.expected, 'expected').revision).toBe('2')
  expect((await fixture.read()).holes[0]?.score?.gross_strokes).toBe(9)
  await other.getByRole('button', { name: 'Sammenlign scorer' }).click()
  await expect(other.getByText('Score på serveren:')).toContainText('9 slag')
  await offlineLayout(other, 'lost-response-conflict', '.pending-scores')
  await other.getByRole('button', { name: 'Behold serverscoren' }).click()
  await expect.poll(async () => (await queueRows(page)).length).toBe(0)
  await expect(page.locator('.score-stepper output strong')).toHaveText('9')
  await expect(page.getByText('Lagret på serveren', { exact: true })).toBeVisible()
  expect(events.errors).toEqual([]); expect(otherEvents.errors).toEqual([])
  await other.close()
})

test('hanging post-ack reads time out without stopping other holes or showing stale values as saved', async ({ page, context }) => {
  const fixture = await offlineFixture(page); const events = offlineEvents(page)
  await page.goto(fixture.url())
  await expect(page.getByRole('button', { name: /Registrer par/ })).toBeEnabled()
  await context.setOffline(true)
  await page.getByRole('button', { name: /Registrer par/ }).click()
  await expect.poll(async () => (await queueRows(page)).length).toBe(1)
  await page.getByRole('button', { name: 'Neste' }).click()
  await page.getByRole('button', { name: 'Legg til ett slag' }).click()
  await expect.poll(async () => (await queueRows(page)).length).toBe(2)
  let release = () => undefined as void
  const pending = new Promise<void>(resolve => { release = resolve })
  await page.route('**/scorecards/*/*/scoring', async route => {
    await pending
    if (!route.request().failure()) await route.continue()
  })
  try {
    await context.setOffline(false)
    await expect.poll(async () => (await queueRows(page)).length, { timeout: 35_000 }).toBe(0)
    await expect(page.locator('.score-stepper output strong')).toHaveText('5')
    await expect(page.getByText('Oppdaterer serverscore · netto venter')).toBeVisible()
    await expect(page.getByRole('button', { name: 'Legg til ett slag' })).toBeDisabled()
    await expect(page.getByRole('button', { name: 'Neste' })).toBeEnabled()
    await offlineLayout(page, 'refresh-wait')
  } finally {
    release()
    await page.unrouteAll({ behavior: 'ignoreErrors' })
  }
  await page.evaluate(() => window.dispatchEvent(new Event('online')))
  await expect(page.getByText('Lagret på serveren', { exact: true })).toBeVisible({ timeout: 35_000 })
  expect(events.errors).toEqual([])
})
