import { expect, test } from '@playwright/test'
import { offlineFixture, offlineEvents, offlineLayout, queueRows } from './offlineSupport'
import { fourBallFixture } from './fourBallSupport'
import { stablefordFixture } from './stablefordSupport'
import { decodePending } from '../src/features/scoring/offline/decode'
test.skip(process.env.GOLF_PREPARED_RETURN_BROWSER !== '1', 'Requires task-owned local API/PostgreSQL and Chrome.')
for (const format of ['stroke', 'team', 'four-ball', 'stableford'] as const) {
  test(`${format}: prepared return retains exact hole, queue revisions and server results`, async ({ page, context, browser }) => {
    const fixture = format === 'four-ball' ? await fourBallFixture(page, browser)
      : format === 'stableford' ? await stablefordFixture(page) : await offlineFixture(page, format === 'team' ? 'team_scramble' : 'individual_stroke_play')
    const events = offlineEvents(page)
    // Load the departure route before coverage loss; this step does not add an app shell.
    await page.goto('/tournaments'); await expect(page.getByRole('heading', { name: fixture.tournament.name, exact: true })).toBeVisible()
    await page.getByRole('link', { name: 'Score', exact: true }).click()
    const par = () => page.getByRole('button', { name: /Registrer par/ }).first()
    const next = () => page.getByRole('button', { name: format === 'four-ball' || format === 'stableford' ? 'Neste hull' : 'Neste', exact: true })
    const hole = (number: number) => format === 'four-ball' || format === 'stableford'
      ? page.getByRole('heading', { name: `Hull ${number} · par 4 · indeks ${number}`, exact: true }) : page.locator('#current-hole-heading').filter({ hasText: String(number) })
    await expect(par()).toBeEnabled()
    await context.setOffline(true)
    await par().click(); await expect.poll(async () => (await queueRows(page)).length).toBe(1)
    await next().click(); await expect(hole(2)).toBeVisible()
    await par().click(); await expect.poll(async () => (await queueRows(page)).length).toBe(2)
    const before = (await queueRows(page)).map(decodePending)
    await next().click(); await expect(hole(3)).toBeVisible()
    await page.getByRole('link', { name: 'Turnering', exact: true }).click()
    await expect(page).toHaveURL(/\/tournaments$/)
    await page.getByRole('link', { name: 'Score', exact: true }).click()
    const back = page.getByRole('button', { name: 'Tilbake til åpnet scorekort' })
    await expect(back).toBeVisible(); await expect(page.locator('.prepared-return')).toContainText('hull 3')
    if (format === 'stroke') await offlineLayout(page, 'prepared-offer', '.prepared-return')
    await back.click(); await expect(hole(3)).toBeVisible()
    await expect(page.getByText(/Bekreftelse venter/).first()).toBeVisible()
    await expect(page.getByLabel('Velg turnering')).toHaveCount(0)
    await par().click(); await expect.poll(async () => (await queueRows(page)).length).toBe(3)
    const after = (await queueRows(page)).map(decodePending)
    for (const previous of before) expect(after.find(item => item.key === previous.key)?.head).toEqual(previous.head)
    await offlineLayout(page, `prepared-${format}`, '.score-page')
    await page.getByRole('button', { name: 'Oppsummering', exact: true }).click()
    for (const confirm of await page.getByRole('button', { name: /^Bekreft/ }).all()) await expect(confirm).toBeDisabled()
    await page.getByRole('button', { name: 'Ett hull', exact: true }).click()
    await expect(hole(3)).toBeVisible()
    await context.setOffline(false)
    await expect.poll(async () => (await queueRows(page)).length, { timeout: 35_000 }).toBe(0)
    await expect(page).not.toHaveURL(/prepared=1/)
    await expect(hole(3)).toBeVisible()
    const card = await fixture.read()
    const values = card.holes.slice(0, 3).map(h => 'players' in h ? h.players[0]?.score?.input : h.score && ('input' in h.score ? h.score.input : { type: 'numeric', gross_strokes: h.score.gross_strokes }))
    expect(values).toEqual(Array.from({ length: 3 }, () => ({ type: 'numeric', gross_strokes: 4 })))
    expect(events.errors).toEqual([])
    expect(events.statuses.filter(status => ![401,409].includes(status))).toEqual([])
    expect(events.failures.every(message => /ERR_INTERNET_DISCONNECTED|ERR_NETWORK_CHANGED|ERR_ABORTED|ERR_FAILED|aborted/i.test(message))).toBe(true)
  })
}

test('fresh locked round removes prepared return at phone and desktop widths', async ({ page, context }) => {
  const fixture = await offlineFixture(page)
  await page.goto('/tournaments'); await page.getByRole('link', { name: 'Score', exact: true }).click()
  await expect(page.getByRole('button', { name: /Registrer par/ })).toBeEnabled()
  for (let h=1; h<=18; h++) await fixture.save(h,4)
  await fixture.mutate(`/api/rounds/${fixture.round.id}/scorecards/${fixture.owner.type}/${fixture.owner.id}/confirm`)
  await fixture.mutate(`/api/rounds/${fixture.round.id}/complete`)
  await fixture.mutate(`/api/rounds/${fixture.round.id}/lock`)
  await expect(page.getByText('Du kan se dette scorekortet, men ikke føre score for det.')).toBeVisible()
  await context.setOffline(true)
  await page.getByRole('link', { name: 'Turnering', exact: true }).click()
  await page.getByRole('link', { name: 'Score', exact: true }).click()
  await expect(page.getByText(/Ingen klargjorte scorekort/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Tilbake til åpnet scorekort' })).toHaveCount(0)
  await offlineLayout(page, 'prepared-locked', '.prepared-return')
})

test('observed denied access cannot return after disconnect', async ({ page, context }) => {
  const fixture = await offlineFixture(page)
  await page.goto('/tournaments'); await page.getByRole('link', { name: 'Score', exact: true }).click()
  await expect(page.getByRole('button', { name: /Registrer par/ })).toBeEnabled()
  await page.route(`**/api/rounds/${fixture.round.id}/score-access`, route=>route.fulfill({status:403,json:{error:{code:'forbidden',message:'Access removed'}}}))
  await page.getByRole('link', { name: 'Turnering', exact: true }).click()
  await page.getByRole('link', { name: 'Score', exact: true }).click()
  await expect(page.getByText('Access removed', {exact:true})).toBeVisible()
  await context.setOffline(true)
  await expect(page.getByText(/Ingen klargjorte scorekort/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Tilbake til åpnet scorekort' })).toHaveCount(0)
  await offlineLayout(page, 'prepared-denied', '.prepared-return')
})

test('prepared action expires while disconnected', async ({ page, context }) => {
  const fixture = await offlineFixture(page)
  await page.route('**/api/auth/session', async route=>{
    const response=await route.fetch();const session=await response.json()
    await route.fulfill({response,json:{...session,expires_at:new Date(Date.now()+4000).toISOString()}})
  })
  await page.goto('/tournaments');await page.getByRole('link', {name:'Score',exact:true}).click()
  await expect(page.getByRole('button', {name:/Registrer par/})).toBeEnabled()
  await context.setOffline(true)
  await page.getByRole('link', {name:'Turnering',exact:true}).click();await page.getByRole('link', {name:'Score',exact:true}).click()
  await expect(page.getByRole('button', {name:'Tilbake til åpnet scorekort'})).toBeVisible()
  await expect(page.getByText(/Ingen klargjorte scorekort/)).toBeVisible({timeout:7000})
  await expect(page.getByRole('button', {name:'Tilbake til åpnet scorekort'})).toHaveCount(0)
  expect(fixture.auth.user_id).toBeTruthy()
})

test('another account and an unprepared card need connection', async ({page,context})=>{
  await offlineFixture(page)
  await page.goto('/tournaments');await page.getByRole('link',{name:'Score',exact:true}).click()
  await expect(page.getByRole('button',{name:/Registrer par/})).toBeEnabled()
  await page.getByRole('button',{name:'Logg ut',exact:true}).click()
  await page.getByLabel('Brukernavn',{exact:true}).fill('anders');await page.getByLabel('Passord',{exact:true}).fill('golf-dev-2026')
  await page.getByRole('button',{name:'Logg inn',exact:true}).click();await expect(page).not.toHaveURL(/\/login/)
  await page.getByRole('link',{name:'Score',exact:true}).click()
  await expect(page.getByText('Turneringen har ingen åpne, fullførte eller låste runder')).toBeVisible()
  await context.setOffline(true)
  await expect(page.getByText(/Ingen klargjorte scorekort/)).toBeVisible()
  await expect(page.getByRole('button',{name:'Tilbake til åpnet scorekort'})).toHaveCount(0)
  await offlineLayout(page,'prepared-empty','.prepared-return')
})

test('Score remains reachable from a results page waiting for offline data', async ({page,context})=>{
  await offlineFixture(page)
  await page.goto('/leaderboard')
  await expect(page.getByRole('link',{name:'Score',exact:true})).not.toHaveAttribute('aria-disabled','true')
  await page.getByRole('link',{name:'Score',exact:true}).click()
  await expect(page.getByRole('button',{name:/Registrer par/})).toBeEnabled()
  await context.setOffline(true)
  await page.getByRole('link',{name:'Resultater',exact:true}).click()
  await expect(page).toHaveURL(/\/leaderboard/)
  await expect(page.getByRole('link',{name:'Score',exact:true})).not.toHaveAttribute('aria-disabled','true')
  await page.getByRole('link',{name:'Score',exact:true}).click()
  await page.getByRole('button',{name:'Tilbake til åpnet scorekort'}).click()
  await expect(page.locator('#current-hole-heading')).toHaveText('1')
})
