import { expect, test } from '@playwright/test'
import { stablefordFixture } from './stablefordSupport'
import { offlineEvents, offlineLayout, queueRows } from './offlineSupport'
import { decodePending } from '../src/features/scoring/offline/decode'
import { decodeTournamentLeaderboard } from '../src/api/leaderboards/tournamentDecoder'

test.skip(process.env.GOLF_STABLEFORD_BROWSER !== '1', 'Requires disposable local API and Chrome')
test('Stableford draft settings, pickup, reconnect conflicts, zero-point confirmation, correction and history', async ({ page }) => {
  const events = offlineEvents(page)
  const fixture = await stablefordFixture(page, async (round, tournamentId) => {
    await page.goto(`/manage/tournaments/${tournamentId}#courses`)
    const settings = page.getByRole('region', { name: `Stableford-innstillinger for ${round.name}` })
    await expect(settings.getByLabel('Handicapandel (0–100 %)')).toHaveValue('100')
    await settings.getByLabel('Handicapandel (0–100 %)').fill('101')
    await expect(settings.getByRole('button', { name: 'Lagre Stableford-innstillinger' })).toBeDisabled()
    await settings.getByLabel('Handicapandel (0–100 %)').fill('50')
    await settings.getByRole('button', { name: 'Lagre Stableford-innstillinger' }).click()
    await expect(settings.getByRole('status')).toContainText('lagret')
    await offlineLayout(page, 'stableford-settings', '.stableford-settings')
  })
  await page.goto(fixture.url())
  const input = page.locator('.four-ball-partner')
  await expect(input).toHaveCount(1)
  await expect(input).toContainText('Spille-HCP 9')
  await offlineLayout(page, 'stableford-empty')
  await input.getByRole('button', { name: 'Registrer par (4)' }).focus()
  await page.keyboard.press('Tab')
  await expect(input.getByRole('button', { name: 'Plukket opp', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(input.getByRole('button', { name: 'Ja, plukket opp' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(input.getByRole('button', { name: 'Plukket opp', exact: true })).toBeFocused()
  await input.getByRole('button', { name: 'Registrer par (4)' }).click()
  await expect.poll(async () => (await fixture.read()).values?.net_points).toBe(3)
  await expect.poll(async () => (await queueRows(page)).length).toBe(0)
  await offlineLayout(page, 'stableford-numeric')
  const original = (await fixture.read()).holes[0]?.score
  await input.getByRole('button', { name: 'Plukket opp', exact: true }).click()
  await expect(input.getByText(/Dette gir 0 brutto-/)).toBeVisible()
  await input.getByRole('button', { name: 'Ja, plukket opp' }).click()
  await expect.poll(async () => (await fixture.read()).values?.net_points).toBe(0)
  expect((await fixture.read()).holes[0]?.score?.id).toBe(original?.id)
  await expect.poll(async () => (await queueRows(page)).length).toBe(0)
  await expect(input.getByRole('button', { name: 'Registrer par (4)' })).toBeEnabled()
  await page.context().setOffline(true)
  await input.getByRole('button', { name: 'Registrer par (4)' }).click()
  await expect.poll(async () => (await queueRows(page)).length).toBe(1)
  expect(decodePending((await queueRows(page))[0]).protocol).toBe('stableford_v1')
  await offlineLayout(page, 'stableford-offline')
  await fixture.save(1, { type: 'numeric', gross_strokes: 9 })
  await page.context().setOffline(false)
  await page.locator('#pending-scores summary').click()
  await page.getByRole('button', { name: 'Sammenlign scorer' }).click()
  await expect(page.getByText('Score på serveren:')).toContainText('9 slag')
  await offlineLayout(page, 'stableford-conflict')
  await page.getByRole('button', { name: 'Behold serverscoren' }).click()
  await expect.poll(async () => (await queueRows(page)).length).toBe(0)
  for (let number = 1; number <= 18; number++) await fixture.save(number, { type: 'no_score' })
  await page.getByRole('button', { name: 'Oppsummering', exact: true }).click()
  await expect(page.getByText('Hull løst')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Bekreft scorekort', exact: true })).toBeEnabled()
  await offlineLayout(page, 'stableford-all-pickups')
  await page.getByRole('button', { name: 'Bekreft scorekort', exact: true }).click()
  await expect.poll(async () => (await fixture.read()).confirmed).toBe(true)
  expect((await fixture.read()).values).toMatchObject({ gross_points: 0, net_points: 0, gross_equivalent: 36, net_equivalent: 36, actual_gross_total: null })
  await fixture.mutate(`/api/rounds/${fixture.round.id}/complete`)
  await page.goto(fixture.url())
  await page.getByRole('button', { name: 'Korriger score' }).click()
  await input.getByRole('button', { name: 'Registrer par (4)' }).click()
  await expect.poll(async () => (await fixture.read()).confirmed).toBe(false)
  expect((await fixture.read()).holes[0]?.score?.id).toBe(original?.id)
  await expect.poll(async () => (await queueRows(page)).length).toBe(0)
  await fixture.mutate(`${fixture.cardPath}/confirm`)
  await fixture.mutate(`/api/rounds/${fixture.round.id}/lock`)
  await page.goto(fixture.url())
  await expect(page.getByText('Runden er låst. Scorekortet er skrivebeskyttet.')).toBeVisible()
  await page.goto(`/tournaments/${fixture.tournament.id}/rounds/${fixture.round.id}/scorecards/player/${fixture.owner.id}?metric=net&view=summary`)
  await expect(page.getByRole('heading', { name: fixture.card.owner_name })).toBeVisible()
  await expect(page.getByText(/Sammenlagtekvivalent: brutto/)).toContainText('+34')
  await offlineLayout(page, 'stableford-locked-history')
  expect(events.errors).toEqual([])
  expect(events.statuses.filter(status => ![401, 409, 503].includes(status))).toEqual([])
  expect(events.failures.every(message => /ERR_INTERNET_DISCONNECTED|ERR_NETWORK_CHANGED|ERR_ABORTED|ERR_FAILED|aborted/i.test(message))).toBe(true)
})
test('Stableford loading and server errors preserve retry, mixed points and equivalent results are labelled', async ({ page }) => {
  const fixture = await stablefordFixture(page, undefined, true)
  const events = offlineEvents(page)
  let release = () => undefined as void
  const wait = new Promise<void>(resolve => { release = resolve })
  await page.route(`**${fixture.cardPath}/scoring`, async route => { await wait; await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'unavailable', message: 'Temporary unavailable' }) }) })
  await page.goto(fixture.url())
  await expect(page.getByText('Laster …', { exact: true })).toBeVisible()
  await offlineLayout(page, 'stableford-loading')
  release()
  await expect(page.getByRole('button', { name: /Prøv igjen/ })).toBeVisible()
  await offlineLayout(page, 'stableford-error')
  await page.unroute(`**${fixture.cardPath}/scoring`)
  await page.getByRole('button', { name: /Prøv igjen/ }).click()
  await expect(page.locator('.four-ball-partner')).toBeVisible()
  for (let number = 1; number <= 18; number++) await fixture.save(number, { type: 'numeric', gross_strokes: 4 })
  await fixture.mutate(`${fixture.cardPath}/confirm`)
  await fixture.mutate(`/api/rounds/${fixture.round.id}/complete`)
  const board = decodeTournamentLeaderboard(await (await page.request.get(`/api/tournaments/${fixture.tournament.id}/leaderboards/net`)).json(), fixture.tournament.id, 'net')
  expect(board.entries[0]?.value).toMatchObject({ type: 'overall_equivalent', selected: -18 })
  await page.goto(`/leaderboard?tournament=${fixture.tournament.id}&metric=net`)
  await expect(page.getByText('54 poeng', { exact: true })).toBeVisible()
  await offlineLayout(page, 'stableford-native-points')
  await page.getByRole('button', { name: 'Turnering', exact: true }).click()
  await expect(page.getByText(/Sammenlagtekvivalent/)).toBeVisible()
  await offlineLayout(page, 'stableford-mixed-overall')
  expect(events.errors).toEqual([])
})

test('Stableford hidden private history and public equivalents do not change after hidden pickup', async ({ page, browser }) => {
  const { decodeObject, decodeString, decodeUuid } = await import('../src/api/decoder')
  const { decodeShareReceipt, decodePublicResults } = await import('../src/api/resultSharing/decoders')
  const fixture = await stablefordFixture(page)
  await fixture.save(1, { type: 'numeric', gross_strokes: 4 })
  await fixture.save(18, { type: 'numeric', gross_strokes: 1 })
  const context = await browser.newContext({ baseURL: 'http://127.0.0.1:5173' })
  try {
    const member = await context.newPage(); const events = offlineEvents(member)
    const invitation = decodeObject(fixture.invitation, 'invitation')
    const registration = await member.request.post(`/api/invitations/${decodeUuid(invitation.id, 'id')}/register`, { data: {
      token: decodeString(invitation.token, 'token'), account: { username: `sf_view_${Date.now()}`, password: fixture.password },
      player: { display_name: 'Medlem uten administratorrettigheter', handicap_index: 0 },
    } })
    expect(registration.status()).toBe(201)
    await member.goto(`/tournaments/${fixture.tournament.id}/rounds/${fixture.round.id}/scorecards/player/${fixture.owner.id}?metric=net&view=summary`)
    const summary = member.getByRole('region', { name: 'Stableford-scorekort' })
    await expect(summary.locator('li')).toHaveCount(9)
    const before = await summary.innerText()
    const receipt = decodeShareReceipt(await (await fixture.mutate(`/api/tournaments/${fixture.tournament.id}/result-share`, { expected_grant_id: null })).json(), fixture.tournament.id)
    const publicRead = async () => decodePublicResults(await (await member.request.post(`/api/public/results/${receipt.grant.id}`, { data: { token: receipt.token, metric: 'net' } })).json(), receipt.grant.id, 'net')
    const publicBefore = await publicRead()
    expect(publicBefore.entries[0]?.value?.type).toBe('overall_equivalent')
    await fixture.save(18, { type: 'no_score' })
    await expect(summary).toHaveText(before, { useInnerText: true })
    expect(await publicRead()).toEqual(publicBefore)
    await offlineLayout(member, 'stableford-hidden-private')
    await member.goto(`/tournaments/${fixture.tournament.id}/results/players/${fixture.owner.id}?metric=net`)
    await expect(member.getByText('Bruttopoeng', { exact: true })).toBeVisible()
    await expect(member.getByText(/ekvivalent/, { exact: false }).first()).toBeVisible()
    await offlineLayout(member, 'stableford-player-history')
    const publicPage = await context.newPage(); const publicEvents = offlineEvents(publicPage)
    await publicPage.goto(`/results/shared/${receipt.grant.id}#token=${receipt.token}`)
    await expect(publicPage.getByText(/Sammenlagtekvivalent/)).toBeVisible()
    await offlineLayout(publicPage, 'stableford-public', '.public-results-page')
    expect(publicEvents.errors).toEqual([]); expect(events.errors).toEqual([])
  } finally { await context.close() }
})
test('the creation wizard exposes individual Stableford with an eighteen-hole course and no team setup', async ({ page }) => {
  await stablefordFixture(page)
  const events = offlineEvents(page)
  await page.goto('/create')
  await page.getByLabel('Turneringsnavn', { exact: true }).fill(`Stableford opprettet i nettleseren ${Date.now()}`)
  await page.getByRole('button', { name: 'Neste', exact: true }).click()
  await page.getByLabel('Spilleform').selectOption('individual_stableford')
  await offlineLayout(page, 'stableford-create-format', '.onboarding-shell')
  await page.getByRole('button', { name: 'Neste', exact: true }).click()
  await expect(page.locator('.review-rounds').getByText(/Stableford \(individuelt, 18 hull\)/)).toBeVisible()
  await page.getByRole('button', { name: 'Opprett turnering', exact: true }).click()
  await expect(page).toHaveURL(/\/manage\/tournaments\//)
  await expect(page.getByText('Stableford · flighter', { exact: true })).toBeVisible()
  expect(events.errors).toEqual([])
})
