import { expect, it } from 'vitest'
import { breakdown, golfer, points, results, roundResult } from './results'
import { roundView, source } from './selections'
import { id, picks, receipt, roundId, tournament, user, view } from '../../features/fantasy/fixtures'
const summary={round_id:roundId,round_number:1,name:'Round',format:'individual_stroke_play',sporting_status:'open',visibility:{mode:'full'},points:{state:'pending',recorded:0}}
const standing={id:user,display_name:'Manager',points:{state:'pending',recorded:-3},rank:null,rounds:[{round_id:roundId,points:{state:'pending',recorded:-3}}]}
const g={player_id:picks[0],display_name:'Player',points:{state:'pending',recorded:-3},rank:null,team_id:null,holes:[],recorded_hole_points:0,placement_points:null,settlement:'playing',match_outcome:null}
const payload={tournament_id:tournament,revision:'a'.repeat(43),round:summary,golfers:[g],managers:[]}
it('rejects malformed points, hidden subtotals and unsafe integers',()=>{expect(points({state:'pending',recorded:-3})).toEqual({state:'pending',recorded:-3});for(const p of [{state:'withheld',total:0},{state:'pending',recorded:Number.MAX_SAFE_INTEGER+1},{state:'omitted_non_finish'},{state:'unknown'}])expect(()=>points(p)).toThrow();expect(points({state:'omitted_non_finish'},'hole',true)).toEqual({state:'omitted_non_finish'})})
it('checks target identity and pre-lock private selections even for admin callers',()=>{expect(()=>roundView({...view,selections:[{user_id:id(90),state:'draft',locked_at:null,receipt:{...receipt,user_id:id(90)}}]},roundId,user)).toThrow();expect(()=>roundView({...view,window:{...view.window,round_id:id(99)}},roundId,user)).toThrow();expect(()=>roundView({...view,carry_forward_preview:{...receipt,user_id:id(90)}},roundId,user)).toThrow()})
it('requires complete distinct picks and coherent source provenance',()=>{expect(()=>roundView({...view,selections:[{user_id:user,state:'draft',locked_at:null,receipt:{...receipt,picks:[...picks.slice(0,3),picks[0]]}}]},roundId,user)).toThrow();expect(()=>roundView({...view,carry_forward_preview:{...receipt,origin:'carried_forward',source_round:null}},roundId,user)).toThrow()})
it('rejects a standings total with missing or mismatched round details',()=>{const overall={tournament_id:tournament,revision:'a'.repeat(43),rules_version:1,rounds:[summary],golfers:[],managers:[standing]};expect(results(overall,tournament).managers).toHaveLength(1);expect(()=>results({...overall,managers:[{...standing,rounds:[]}]},tournament)).toThrow();expect(()=>breakdown({tournament_id:tournament,revision:'a'.repeat(43),standing:{...standing,id:picks[0]},rounds:[{round: {...summary,round_id:id(99)},result:g}]},tournament,picks[0]??'',golfer)).toThrow()})
it('rejects hidden round facts but preserves permitted front-nine hole subtotals',()=>{const hidden={...summary,sporting_status:null,visibility:{mode:'front_nine'},points:{state:'withheld'}};const hiddenG={...g,points:{state:'withheld'},settlement:'withheld',recorded_hole_points:-3,holes:[{hole_id:id(40),hole_number:1,par:4,category:'triple_bogey',net_strokes:7,points:{state:'settled',total:-3}},{hole_id:id(41),hole_number:10,par:4,category:null,net_strokes:null,points:{state:'withheld'}}]};expect(roundResult({...payload,round:hidden,golfers:[hiddenG]},tournament,roundId).golfers[0]?.recorded_hole_points).toBe(-3);for(const bad of [{...hiddenG,placement_points:1},{...hiddenG,match_outcome:'win'},{...hiddenG,settlement:'confirmed'},{...hiddenG,holes:[{...hiddenG.holes[1],net_strokes:3}]}])expect(()=>roundResult({...payload,round:hidden,golfers:[bad]},tournament,roundId)).toThrow();expect(()=>roundResult({...payload,round:{...hidden,sporting_status:'locked'},golfers:[hiddenG]},tournament,roundId)).toThrow()})
it('requires source token and exact round/owner identity',()=>{const s={round_id:roundId,owner_kind:'player',owner_id:picks[0],source_token:'a'.repeat(43),disposition:null,disposition_current:false};expect(source(s,roundId,'player',picks[0]??'').disposition).toBeNull();expect(()=>source({...s,owner_kind:'team'},roundId,'player',picks[0]??'')).toThrow();expect(()=>source({...s,source_token:'short'},roundId,'player',picks[0]??'')).toThrow()})
