import { QueryClient, QueryObserver } from '@tanstack/react-query'
import { expect, it, vi } from 'vitest'
import { authKeys } from '../auth'
import { ApiHttpError } from '../http'
import { handleTournamentLiveSignal } from '../liveInvalidation'
import { denyPrivateResults, loadPrivateResult } from '../privateResults'
import { fantasyKeys } from './index'
import { publishSessionTransition } from '../../features/auth/sessionTransition'
import { session, tournament } from '../../features/fantasy/fixtures'
it.each(['score','match','change'] as const)('invalidates Fantasy selection/result/source keys on %s',async signal=>{const client=new QueryClient();const keys=['round','results','source'].map(k=>fantasyKeys.query(session.user_id,tournament,k));for(const key of keys)client.setQueryData(key,{private:true});await handleTournamentLiveSignal(client,session.user_id,signal==='change'?'tournament':signal);for(const key of keys)expect(client.getQueryState(key)?.isInvalidated).toBe(true);client.clear()})
it.each(['visibility','open','error'] as const)('synchronously erases all Fantasy private projections on %s',async signal=>{const client=new QueryClient();const keys=['round','results','source'].map(k=>fantasyKeys.query(session.user_id,tournament,k));for(const key of keys)client.setQueryData(key,{private:true});const promise=handleTournamentLiveSignal(client,session.user_id,signal);for(const key of keys)expect(client.getQueryData(key)).toBeUndefined();await promise;client.clear()})
it('clears Fantasy data on same-account renewal while preserving unrelated workspace behavior',()=>{const client=new QueryClient();client.setQueryData(authKeys.session,session);const key=fantasyKeys.query(session.user_id,tournament,'source');client.setQueryData(key,{private:true});publishSessionTransition(client,{...session,csrf_token:'renewed'});expect(client.getQueryData(key)).toBeUndefined();client.clear()})
it('denies sibling Fantasy caches and fences a held successful read',async()=>{const client=new QueryClient({defaultOptions:{queries:{retry:false}}});const resultKey=fantasyKeys.query(session.user_id,tournament,'results'),sourceKey=fantasyKeys.query(session.user_id,tournament,'source');client.setQueryData(resultKey,{private:'old'});client.setQueryData(sourceKey,{token:'old'});let release:(value:{private:string})=>void=()=>{};const observer=new QueryObserver(client,{queryKey:resultKey,queryFn:({signal})=>loadPrivateResult(client,{userId:session.user_id,tournamentId:tournament},resultKey,signal,()=>new Promise(resolve=>{release=resolve}))});const stop=observer.subscribe(()=>{});await vi.waitFor(()=>expect(client.getQueryState(resultKey)?.fetchStatus).toBe('fetching'));denyPrivateResults(client,{userId:session.user_id,tournamentId:tournament},sourceKey,new ApiHttpError(403,'denied','denied'));release({private:'held'});await new Promise(resolve=>setTimeout(resolve,0));expect(client.getQueryData(resultKey)).toBeUndefined();expect(client.getQueryData(sourceKey)).toBeUndefined();stop();client.clear()})
