// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { authKeys } from '../../api/auth'
import { fantasyApi, type RoundResult, type Source } from '../../api/fantasy'
import { ApiHttpError } from '../../api/http'
import { AuthContext } from '../auth/authContext'
import { FantasySettlement } from './FantasySettlement'
import { id, picks, roundId, session, tournament } from './fixtures'
vi.mock('../../api/fantasy',async original=>({...await original<typeof import('../../api/fantasy')>(),fantasyApi:{source:vi.fn(),dispose:vi.fn()}}))
let client:QueryClient
const source:Source={round_id:roundId,owner_kind:'team',owner_id:id(70),source_token:'a'.repeat(43),disposition:null,disposition_current:false}
const results:RoundResult={tournament_id:tournament,revision:'a'.repeat(43),round:{round_id:roundId,round_number:1,name:'Team',format:'team_scramble',sporting_status:'open',visibility:{mode:'full'},points:{state:'pending',recorded:0}},golfers:[{player_id:picks[0]??'',display_name:'Partner en',team_id:id(70),points:{state:'pending',recorded:0},rank:null,holes:[],recorded_hole_points:0,placement_points:null,settlement:'playing',match_outcome:null},{player_id:picks[1]??'',display_name:'Uten lag',team_id:null,points:{state:'not_participating'},rank:null,holes:[],recorded_hole_points:null,placement_points:null,settlement:null,match_outcome:null}],managers:[]}
const recorded:Source={...source,disposition_current:true,disposition:{id:id(71),actor_id:session.user_id,disposed:true,correction:false,reason:'Stoppet',created_at:'2026-01-01T12:00:00Z'}}
beforeEach(()=>{vi.resetAllMocks();client=new QueryClient({defaultOptions:{queries:{retry:false}}});client.setQueryData(authKeys.session,session);vi.mocked(fantasyApi.source).mockResolvedValue(source)})
afterEach(()=>{cleanup();client.clear()})
function tree(){return render(<QueryClientProvider client={client}><AuthContext.Provider value={{session,loading:false,error:null,signIn:vi.fn(),establishSession:vi.fn(),signOut:vi.fn(),retry:vi.fn()}}><FantasySettlement tournament={tournament} results={results} refreshing={false}/></AuthContext.Provider></QueryClientProvider>)}
async function choose(){fireEvent.change(screen.getByLabelText('Spiller eller lag'),{target:{value:`team:${source.owner_id}`}});await screen.findByLabelText('Begrunnelse (maks. 500 byte)');fireEvent.change(screen.getByLabelText('Begrunnelse (maks. 500 byte)'),{target:{value:'Stoppet'}})}
it('offers only actual round owners and preserves accepted outcome through source invalidation',async()=>{vi.mocked(fantasyApi.dispose).mockImplementation(async()=>{vi.mocked(fantasyApi.source).mockResolvedValue(recorded);return recorded});tree();expect(screen.queryByRole('option',{name:'Uten lag'})).toBeNull();await choose();fireEvent.click(screen.getByRole('button',{name:'Registrer ikke fullført'}));await screen.findByText(/Registrert som ikke fullført/);await screen.findByText('Handlingen er bekreftet. Visningen er oppdatert.');expect(screen.getByLabelText('Spiller eller lag')).toHaveProperty('value',`team:${source.owner_id}`);expect(screen.getByRole('button',{name:'Trekk tilbake ikke-fullført'})).toHaveProperty('disabled',true)})
it.each([409,503])('retains failure feedback and selected owner through refresh after %s',async status=>{vi.mocked(fantasyApi.dispose).mockRejectedValue(new ApiHttpError(status,status===409?'fantasy_conflict':'unavailable','error'));tree();await choose();fireEvent.click(screen.getByRole('button',{name:'Registrer ikke fullført'}));await waitFor(()=>expect(fantasyApi.source).toHaveBeenCalledTimes(2));expect(screen.getByRole('alert').textContent).toMatch(status===409?/Grunnlaget ble endret/:/Kunne ikke hente en bekreftelse/);expect(screen.getByLabelText('Spiller eller lag')).toHaveProperty('value',`team:${source.owner_id}`)})
it('requires a new reason and correction attestation after a stale source changes',async()=>{vi.mocked(fantasyApi.source).mockResolvedValue({...recorded,source_token:'b'.repeat(43),disposition_current:false});vi.mocked(fantasyApi.dispose).mockResolvedValue(recorded);tree();await choose();expect(screen.getByText(/Avgjørelsen er foreldet/)).toBeTruthy();expect(screen.getByRole('button',{name:'Bekreft ikke fullført på nytt'})).toHaveProperty('disabled',true);fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Bekreft ikke fullført på nytt'}));await waitFor(()=>expect(fantasyApi.dispose).toHaveBeenCalledWith(tournament,roundId,'team',source.owner_id,{expected_source_token:'b'.repeat(43),disposed:true,correction:true,reason:'Stoppet'},session.csrf_token))})
